version: "3.8"

networks:
  connect:
    driver: bridge

volumes:
  postgres-data:

services:
  postgres:
    image: postgres:17-alpine3.20
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME:-connect_app}
      POSTGRES_USER: ${POSTGRES_USER:-default}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-default}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - connect
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_DB_USERNAME:-default} -d connect_app"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G