spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB_NAME:connect_app}
    username: ${POSTGRES_USER:default}
    password: ${POSTGRES_PASSWORD:default}
    driver-class-name: org.postgresql.Driver